# Basic
title: Wu Bigo
subtitle: Today I Learned
description: A collection of concise write-ups build from http://bigo.github.io .These are things that don't really warrant a full blog post
# 头像里面的标题
avatarTitle: Bigo
# 头像里面的描述
avatarDesc: Iaas / Paas /Big Data
url: "http://wubigo.com"

# Comment
comment:
    disqus: wubigo
    # uyan: 2143225  # 有言id,登录有言官网申请

# Social
social:
    github: wubigo
    # twitter:
    mail: wubigo@gmail.com



# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  帮忙star一下，感谢~😆 地址： https://github.com/leopardpan/leopardpan.github.io
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: Home

# Navigation buttons in the front page.s
nav:
    - {title: Archive, description: archive, url: '/archive'}
    - {title: Tags, description: tags, url: '/tags'}
    - {title: About, description: about, url: '/about'}


# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"
